global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'resource-provisioner-consumer'
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ['resource-provisioner-consumer:5000']