apiVersion: v1
kind: Service
metadata:
  name: cloud-ops-manager-api
spec:
  type: NodePort
  selector:
    app: cloud-ops-manager-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000