services:
  resource-provisioner-consumer:
    container_name: resource-provisioner-consumer
    build:
      args:
        - GO_VERSION=${GO_VERSION:-1.24}
      context: .
      dockerfile: Dockerfile.dev
    ports: [ ]
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - internal-network
    restart: on-failure